### ISSUE TITLE
Can't Add Text as Child Object

### ISSUE THREAD

**Issue by jayliu50** [werwack/storyliner-support#12]
## Infos on the context
- **Add-on edition:** Storyboard
- **Add-on version:** V 1.1.30
- Blender version, from installer or from zip: 4.2.1 Zip
- Blender was launched in Admin mode? No
- **OS:** Windows 10
- Bug was also on previous versions (I don't know / No / Yes, seen on version x.x): Don't know.

## Describe the bug
Error seen when trying to add a text object as a child.

## To Reproduce
1. Create Shot
2. Create text using Blender's native Add Text (rotate it in place, etc)
2. Or start by loading in [Storyboard2.zip](https://github.com/user-attachments/files/16822339/Storyboard2.zip)
3. Under Shot / Storyboard, Under Children Objects, click on the link icon
4. Bug: the error message is shown in the console

```
Python: Traceback (most recent call last):
  File "C:\Users\user\AppData\Roaming\Blender Foundation\Blender\4.2\scripts\addons\storyliner\features\storyboard\operators\storyboardframe_operators.py", line 204, in execute
    utils_storyboard.linkObjectToStbFrame(shot, context.active_object, parentEntity="CANVAS")
  File "C:\Users\user\AppData\Roaming\Blender Foundation\Blender\4.2\scripts\addons\storyliner\utils\utils_storyboard.py", line 104, in linkObjectToStbFrame
    stbf_empty = utils_greasepencil.get_greasepencil_child(shot.camera, childType="EMPTY")
                 ^^^^^^^^^^^^^^^^^^
NameError: name 'utils_greasepencil' is not defined
```

## Expected behavior
Add the selected text object as a child object.

## Additional context, screenshots...
User is new to storyliner and grease pencil.

**Comment by werwack** [comment]
Thank you for the report. A code import issue. It is fixed in SL V1.1.31, coming soon.

**Comment by werwack** [comment]
@jayliu50 I added a beta version of SL with all the fixes in the list of the files on the user product page on Blender Market. It's V1-1-32_Beta.zip.
Can you please get it and let me know if it fixes this bug? Thanks a lot!

**Comment by jayliu50** [comment]
1.32 beta fixes this issue. Thank you so much.
