### ISSUE TITLE
error on install Storyliner on Osx - in blender 4.1.1

### ISSUE THREAD

**Issue by Patricktosborne** [werwack/storyliner-support#3]
## Infos on the context

- **Add-on version:** V 1.0.52
- Blender version, from DMG installer or from zip:  4.1.1  DMG installer
- Blender was launched in Admin mode? Osx doesn't have admin mode as far as I can tell
- **OS:**  OSX 
- Bug was also on previous versions (I don't know / No / Yes, seen on version x.x): Don't know

## Describe the bug
Addon does not install. 

## To Reproduce
1. open blender 4.1.1
2. from preferences menue - Install addon - locate addon
3. Click check box to load

## Expected behavior
I expected to load th addon. 

## Additional context, screenshots...
traceback error 👍 
Traceback (most recent call last):
  File "/Applications/Blender.app/Contents/Resources/4.1/scripts/modules/addon_utils.py", line 444, in enable
    mod.register()
  File "/Users/patricknsa/Library/Application Support/Blender/4.1/scripts/addons/storyliner/__init__.py", line 44, in register
    register_addon.register()
  File "/Users/patricknsa/Library/Application Support/Blender/4.1/scripts/addons/storyliner/addon_install_and_register/register_addon.py", line 225, in register
    from ..features import stampinfo
  File "/Users/patricknsa/Library/Application Support/Blender/4.1/scripts/addons/storyliner/features/stampinfo/__init__.py", line 21, in <module>
    from .properties import stampinfo_props
  File "/Users/patricknsa/Library/Application Support/Blender/4.1/scripts/addons/storyliner/features/stampinfo/properties/stampinfo_props.py", line 25, in <module>
    from ..properties import infoImage
  File "/Users/patricknsa/Library/Application Support/Blender/4.1/scripts/addons/storyliner/features/stampinfo/properties/infoImage.py", line 23, in <module>
    from PIL import Image, ImageDraw, ImageFont
  File "/Users/patricknsa/.local/lib/python3.11/site-packages/PIL/Image.py", line 88, in <module>
    from . import _imaging as core
ImportError: dlopen(/Users/patricknsa/.local/lib/python3.11/site-packages/PIL/_imaging.cpython-311-darwin.so, 0x0002): tried: '/Users/patricknsa/.local/lib/python3.11/site-packages/PIL/_imaging.cpython-311-darwin.so' (mach-o file, but is an incompatible architecture (have 'x86_64', need 'arm64')), '/System/Volumes/Preboot/Cryptexes/OS/Users/patricknsa/.local/lib/python3.11/site-packages/PIL/_imaging.cpython-311-darwin.so' (no such file), '/Users/patricknsa/.local/lib/python3.11/site-packages/PIL/_imaging.cpython-311-darwin.so' (mach-o file, but is an incompatible architecture (have 'x86_64', need 'arm64'))

Traceback (most recent call last):
  File "/Applications/Blender.app/Contents/Resources/4.1/scripts/modules/addon_utils.py", line 444, in enable
    mod.register()
  File "/Users/patricknsa/Library/Application Support/Blender/4.1/scripts/addons/storyliner/__init__.py", line 44, in register
    register_addon.register()
  File "/Users/patricknsa/Library/Application Support/Blender/4.1/scripts/addons/storyliner/addon_install_and_register/register_addon.py", line 120, in register
    utils_ui.register()
  File "/Users/patricknsa/Library/Application Support/Blender/4.1/scripts/addons/storyliner/utils/utils_ui.py", line 1412, in register
    bpy.utils.register_class(cls)
ValueError: register_class(...): already registered as a subclass 'WKSL_PT_QuickHelp'

**Comment by werwack** [comment]
Hi @Patricktosborne 
Thank you for reporting the issue.
Apparently the PIL library has not been installed, or for some reason the code is not looking into the right folder.
As you may have read on the doc, the development of StoryLiner is done on Windows, so I have low latitude to reproduce the issue. One of the beta testers is on Mac and has not faced this error. Maybe he has a trick to do the equivalent of Admin mode on Windows, In any cases, the add-on should still be able to load.

I'll investigate that at the beginning of the week.

**Comment by werwack** [comment]
Hi @Patricktosborne,
I sent you a version of SL with a possible fix by e-mail. Please tell me if that fixes at least the error message.
Thank you

**Comment by Patricktosborne** [comment]
thanks - I checked spam and other folders and don't think I see that email.
was it sent to ***@***.*** ?

**Comment by werwack** [comment]
It was sent to the e-mail you provided when purchasing SL. I sent another one to you today.
Maybe it would be easier / faster if you could contact me on the discord...

**Comment by werwack** [comment]
This issue doesn't seem up-to-date anymore. I close it.
